website/views.py
from flask import Flask, render_template, request, url_for, redirect, flash, Blueprint
from flask_login import login_required, current_user
from . import posts, enquiries
from .models import Enquiry, Post

views = Blueprint("views", __name__)

@ views.route('/', methods=['GET', 'POST'])
@ views.route('/home', methods=['GET', 'POST'])
def index():
    blog_posts = posts.find()

    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        phone = request.form.get('phone')
        message = request.form.get('message')

        if not name or not email or not phone or not message:
            flash('All fields required', category="error")
            return redirect(url_for('views.index'))
        else:
            enquiry = Enquiry(name, email, phone, message)
            enquiries.insert_one(enquiry.json())
            flash('Enquiry Received', category="success")
            return redirect(url_for('views.index'))

    return render_template("index.html", user=current_user, posts=blog_posts)


@ views.route('/write', methods=['GET', 'POST'])
@login_required
def write():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        imgURL = request.form.get('imgURL')

        if not title:
            flash('Title cannot be empty', category="error")
            return redirect(url_for('views.write'))
        if not content:
            flash('Post cannot be empty', category="error")
            return redirect(url_for('views.write'))
        else:
            new_post = Post(current_user.username, title, content, imgURL)
            posts.insert_one(new_post.json())
            flash('Post Created', category="success")
            return redirect(url_for('views.index'))
    return render_template("write.html", user=current_user)


@ views.route('/posts/<string:post_id>')
def single_post(post_id):
    single_post = posts.find_one({'_id': post_id})
    return render_template("single_post.html", user=current_user, post=single_post)


@ views.route('/delete/<string:post_id>')
def delete(post_id):
    delete_post = posts.find_one({'_id': post_id})
    if not current_user.is_authenticated:
        flash("You do not have permission to delete this post", category="error")
        return redirect(url_for('single_post', post_id=post_id))
    elif current_user.username != delete_post['username'][0]:
        flash("You do not have permission to delete this post", category="error")
        return redirect(url_for('single_post', post_id=post_id))
    else:
        posts.delete_one(delete_post)
        flash('Post Deleted', category="success")
    return redirect(url_for('views.index'))


@ views.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == "GET":
        return redirect(url_for('views.index'))
    else:
        posts.create_index([('title', 'text')])
        search = request.form.get('search')
        results = posts.find({"$text": {"$search": search}})
        count = posts.count_documents({"$text": {"$search": search}})

        if count != 0:
            return render_template('index.html', posts=results, user=current_user)
        else:
            message = "Not Found"
            return render_template('index.html', message=message, user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;600;700&family=Poppins:wght@400;700&family=Silkscreen&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/styles.css" />
    <title>Home</title>
</head>
<body>
    <!-- navbar -->
    <div class="top">
        <div class="topLeft">
            <!-- <i class="topIcon fa-solid fa-envelope"></i> -->
            <i class="topIcon fa-brands fa-github"></i>
            <i class="topIcon fa-brands fa-linkedin"></i>
        </div>
        <div class="topCenter">
            <ul class='topList'>
                <a href="/home" class='topListItem'>HOME</a>
                <a href="/write"class='topListItem'>WRITE</a>
                {% if user.is_authenticated%}
                <a href="/logout" class='topListItem'>LOGOUT</a>
                {% else %}
                <a href="/login" class='topListItem'>LOGIN</a>
                <a href="/register" class='topListItem'>REGISTER</a>
                {% endif %}
            </ul>
        </div>
        <div class="topRight">
        <form action="{{url_for('views.search')}}" method="post">
                <input class="topSearchBar" type="text" name="search" placeholder="Search...">
                <button type="submit" style="all:unset"><i class="topSearch fa-solid fa-magnifying-glass"></i></button>
        </form>
        </div>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert" align="center">
            <span><i class="fa-solid fa-triangle-exclamation"></i></i></span>
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissible fade show" role="alert" align="center">
            
        <span><i class="fa-solid fa-circle-check"></i>&nbsp</span>
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <!-- content -->
    {% block content %} 
    {% endblock %}

    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"
  ></script>

</body>
</html>

website/templates/index.html
{% extends "base.html" %}
{% block content %} 

<div>
    <div class="header">
        <span class="header-title">Welcome {{user.username}}</span>
        <img class="header-image" src="https://img.freepik.com/free-vector/hand-painted-watercolor-pastel-sky-background_23-2148902771.jpg?w=2000">
    </div>
    <div class="blog-container">
        {% for post in posts %}
        <div class="card">
            <div class="blog-image">
                <img src={{post.imgURL}}>
            </div>

            <div class="blog-text">
                <a href="/posts/{{post._id}}">{{post.title}}</a>
                <span>{{post.created_date}}</span>
                <p>{{post.content}}</p>
            </div>       
        </div>
        {% endfor %}

        {% if message %}
        <div class="blog-message">
        {{ message }}
        </div>
        {% endif %}
        

        <!-- footer -->

    </div>

    <div class="footer">
        <div class="footer-about">
            <span class="about-title">About Us</span>
            <p>David and Ellie's group project for CS203</p>
            <br>
            <p>This is a blog project using Flask framework inspired by Tech with Tim's flask-blog and Lama Dev's React-blog application</p>
            <div class="footer-icons">
                <!-- <i class="topIcon fa-solid fa-envelope"></i> -->
                <i class="topIcon fa-brands fa-github"></i>
                <i class="topIcon fa-brands fa-linkedin"></i>
            </div>
        </div>
        <div class="footer-email">
            <h2>Get in touch</h2>
            <form action="{{url_for('views.index')}}" method="post">
                <input class="input-field" type="text" id="name" name="name" placeholder="Enter your name">
                <input class="input-field" type="email" id="email" name="email" placeholder="Enter your email">
                <input class="input-field" type="text" id="phone" name="phone" placeholder="Enter your contact number">
                <textarea id="message" name="message" class="textarea-field" placeholder="Enter your message"></textarea>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block content %} 

    <div class="login">
        <span class="loginTitle">Login</span>
        <form method="POST" action="{{url_for('auth.login')}}" class="loginForm">
            <label>Email:</label>
            <input class="loginInput" name="email" type="text" placeholder="Enter your email..." />
            <label>Password:</label>
            <input class="loginInput" name="password" type="password" placeholder="Enter your password..." />
            <button class="loginButton">Login</button>
        </form>
    </div>
    
{% endblock %}

website/templates/register.html
{% extends "base.html" %}
{% block content %} 

{% if message %}
  <div>
    <p>{{message}}</p>
  </div>
{% endif %}
    
    <div class="register">
        <span class="registerTitle">Register</span>
        <form action="{{url_for('auth.register')}}" method="post" class="registerForm">
          <label>Username:</label>
          <input class="registerInput" type="text" name="username" placeholder="Enter your username..." />
          <label>Email:</label>
          <input class="registerInput" type="text" name="email" placeholder="Enter your email..." />
          <label>Password:</label>
          <input class="registerInput" type="password" name="password" placeholder="Enter your password..." />
          <button class="registerButton">Register</button>
        </form>
      </div>


{% endblock %}

website/templates/single_post.html
{% extends "base.html" %}
{% block content %} 

    <div class="singlePost">
        <div class="singlePostWrapper">
            <img class="singlePostImg" src="{{post.imgURL}}" alt="d12" />
            <h1 class="singlePostTitle">
                {{post.title}}
                <div class="singlePostEdit">
                    <a class="button" href="/delete/{{post._id}}"><i class="singlePostIcon fa-regular fa-trash-can"></i></a>
                </div>
            </h1>
        <div class="singlePostInfo">
            <span class="singlePostAuthor">Author: <b>{{post.username[0]}}</b></span>
            <span class="singlePostDate">{{post.created_date}}</span>
        </div>
        <p class="singlePostDesc">{{post.content}}</p>
        </div>
    </div>

{% endblock %}

website/templates/write.html
{% extends "base.html" %}
{% block content %} 

    <div class="write">
       <form method='POST' action="{{url_for('views.write')}}" class="writeForm">
        <div class="writeFormGroup">
            <input type="text" name = "title" placeholder="Title" class="writeInput" autofocus>
        </div>
        <div class="writeFormGroup">
            <textarea placeholder="Tell your story..." type="text" name = "content" class="writeInput writeText"></textarea>
        </div>
       
        <!-- <div class="writeFormGroup">
            <label for="fileInput">
                <i class="writeIcon fa-solid fa-file-arrow-up"></i>
                <span>Upload File</span>
            </label>
            <input type="file" id="fileInput" style="display:none">
        </div> -->

        <div class="writeFormGroup">
            <input placeholder="Image URL" type="text" name = "imgURL" class="writeImageURL">
        </div>

        <div class="writeButton">
            <button class="writeSubmit">Publish</button>
        </div>
       </form>
    </div>
    
{% endblock %}